### ISSUE TITLE
Instruction

### ISSUE THREAD

**Issue by maxnachamkin** [glaszig/soundmanager-rails#2]
Awesome stuff. Could you go into more detail with how to actually put the player on your site? I included the gem, but where do I go from there?

**Comment by glaszig** [comment]
As this is just a wrapper gem for the soundmanager2 library you can find further help in its [api docs](http://www.schillmania.com/projects/soundmanager2/doc/getstarted/#basic-inclusion).
Note that you don't need to configure the `soundManager.url` as the gem [already does it](https://github.com/glaszig/soundmanager-rails/blob/master/lib/assets/javascripts/soundmanager.js.erb).

I do not (yet) provide view helpers for Rails to add player controls to templates.
