### ISSUE TITLE
A hint about the 'thin' webserver

### ISSUE THREAD

**Issue by TJamesCorcoran** [glaszig/soundmanager-rails#8]
I installed  soundmanager-rails and couldn't get it to work.  Specifically, when I did

soundManager.createSound()  inside soundManager.onready(), everything worked, but when I later called soundManager.play(), I got an error saying that the file couldn't be loaded...even though I could load it into chrome from the URL bar using either a relative or absolute URL.

After five hours of debugging and setting breakpoints I finally realized what was going on: the 'thin' webserver that I use in rails development seems to not send MIME headers for mp3 files, and this confuses soundmanager.

The solution was to specify the sound file URLs to an absolute URL of the production box, which uses nginx.

I hope this saves someone some time.

**Comment by glaszig** [comment]
i'm not sure about your setup but you might have to set the response's content type in your ruby app unless your serving the mp3 through `Rack::File` which should detect the type based on the file's extension.
